name: Deploy docker container to azure

on:
  push:
    branches: [ "main" ]
    paths: 
      - "./"
  workflow_dispatch:

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with: 
        creds: ${{ secrets.creatorapisecret }}
        
    - name: Build and deploy Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{github.workspace}}
        acrName: CreatorAPI
        containerAppName: creator-api
        resourceGroup: platform
    
